# .github/workflows/ci.yaml

name: CI

on:
  push:
    # branches: [main, develop]
    branches-ignore: []
  pull_request:
    branches: [main, develop]
    # branches-ignore: []

jobs:
  test:
    name: Node.js v${{ matrix.nodejs }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nodejs: [10, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.nodejs }}

      - name: Install
        run: |
          npm install
        # npm install -g nyc
      # - name: Compiles
      #   run: npm run build

      - name: Test with reporting
        if: matrix.nodejs >= 14
        run: |
          npm run test:ci-report
          nyc report --reporter=text-lcov > coverage.lcov
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
